from typing import Any, Callable, Dict, Optional

from html.parser import HTMLParser

try:
    import html5lib
except ModuleNotFoundError:  # pragma: no cover - fallback exercised in tests
    html5lib = None  # type: ignore[assignment]

from guardrails.validator_base import (
    FailResult,
    PassResult,
    ValidationResult,
    Validator,
    register_validator,
)


@register_validator(name="guardrails/valid_html", data_type="string")
class ValidHtml(Validator):
    """# Overview

    | Developed by | Alejandro Esquivel |
    | Date of development | Jul 09, 2024 |
    | Validator type | Format |
    | License | Apache 2 |
    | Input/Output | Output |

    # Description
    This validator ensures that a generated output is parseable as valid HTML.

    ## Requirements

    * Dependencies:
        - html5lib>=1.1,<2.0

    # Installation

    ```bash
    $ guardrails hub install hub://guardrails/valid_html
    ```

    # Usage Examples

    ## Validating string output via Python

    In this example, we apply the validator to a string output generated by an LLM.

    ```python
    # Import Guard and Validator
    from guardrails.hub import ValidHtml
    from guardrails import Guard

    # Setup Guard
    guard = Guard().use(
        ValidHtml()
    )

    guard.validate("<p>hello</p>")  # Validator passes
    guard.validate("<phello</p>")  # Validator fails
    ```
    """  

    def __init__(
        self,
        *,
        strict: bool = True,
        on_fail: Optional[Callable[..., Any]] = None,
    ) -> None:
        """Create a new ValidHtml validator.

        Args:
            strict: When True, raise on the first HTML parsing error. When False,
                html5lib will attempt to recover from malformed markup.
            on_fail: Optional corrective action to run when validation fails.
        """

        super().__init__(on_fail=on_fail)
        self.strict = strict

    def validate(
        self, value: Any, metadata: Optional[Dict[str, Any]] = None
    ) -> ValidationResult:
        if not isinstance(value, str):
            return FailResult(
                error_message="Value provided to ValidHtml must be a string containing HTML.",
            )

        if html5lib is not None:
            parser = html5lib.HTMLParser(strict=self.strict)
            try:
                parser.parse(value)
            except html5lib.html5parser.ParseError as parse_error:  # type: ignore[attr-defined]
                fallback_parser = html5lib.HTMLParser(strict=self.strict)
                try:
                    fallback_parser.parse(f"<!DOCTYPE html>{value}")
                except html5lib.html5parser.ParseError as fallback_error:  # type: ignore[attr-defined]
                    return FailResult(
                        error_message=(
                            "Value provided is not valid HTML. Reason: "
                            f"{fallback_error if self.strict else parse_error}"
                        ),
                    )
            except Exception as exc:  # Catch unexpected parser errors
                return FailResult(
                    error_message=f"Unexpected error while validating HTML: {exc}",
                )
            return PassResult()

        try:
            _validate_with_stdlib(value, strict=self.strict)
        except _HTMLValidationError as exc:
            return FailResult(error_message=str(exc))
        except Exception as exc:  # Catch unexpected parser errors
            return FailResult(
                error_message=f"Unexpected error while validating HTML: {exc}",
            )

        return PassResult()


class _HTMLValidationError(Exception):
    """Raised when the stdlib fallback detects malformed HTML."""


_VOID_ELEMENTS = {
    "area",
    "base",
    "br",
    "col",
    "embed",
    "hr",
    "img",
    "input",
    "keygen",
    "link",
    "meta",
    "param",
    "source",
    "track",
    "wbr",
}


class _StdlibHTMLValidator(HTMLParser):
    def __init__(self, *, strict: bool) -> None:
        super().__init__(convert_charrefs=True)
        self._strict = strict
        self._stack: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, Optional[str]]]) -> None:
        tag = tag.lower()
        if tag in _VOID_ELEMENTS:
            return
        self._stack.append(tag)

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()

        if not self._stack:
            self._raise(f"Unexpected closing tag </{tag}> with no matching opener.")

        opener = self._stack.pop()
        if opener != tag:
            self._raise(
                f"Closing tag </{tag}> does not match the most recent opener <{opener}>."
            )

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, Optional[str]]]) -> None:
        # Self-closing tags are already balanced, nothing to track.
        return

    def close(self) -> None:
        super().close()
        if self._stack:
            missing = ", ".join(f"</{tag}>" for tag in reversed(self._stack))
            self._raise(f"Unclosed tags detected: expected {missing}.")

    def error(self, message: str) -> None:  # pragma: no cover - maintained for API parity
        self._raise(f"HTML parsing error: {message}")

    def _raise(self, message: str) -> None:
        raise _HTMLValidationError(message)


def _validate_with_stdlib(value: str, *, strict: bool) -> None:
    parser = _StdlibHTMLValidator(strict=strict)
    parser.feed(value)
    parser.close()
